name: Question
description: Ask a question about using the Balkan On Demand addon
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!
        
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation
        - Configuration
        - Content availability
        - Playback issues
        - General usage
        - Other
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question
      placeholder: What have you tried? What documentation have you checked?
    validations:
      required: false
